[package]
name = "cryptol_prelude"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apint = "0.2.0"
num = "0.4.0"
