[package]
name    = "cry_rts"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cry_rts"
path = "exe/main.rs"

[lib]
path = "src/lib.rs"

[dependencies]
num = "0.4.0"
dword = { path = "../dword" }

