[package]
name    = "dword"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"
license-files = "../LICENSE"

[dependencies]
num  = "0.4.0"

[dev-dependencies]
proptest = "1.2"
rand = "0.8.5"

